spring:
  application:
    name: eureka

# Configure this Discovery Server
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
    # 个配置一般为服务刷新时间配置的三倍，默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-renewal-interval-in-seconds: 5
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@localhost:7001/eureka/
  server:
    # 关闭保护机制，默认true
    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000
    eviction-interval-timer-in-ms: 5000
    # 禁用readOnlyCacheMap（中小集群可以直接关闭，但在大集群中建议还是开启）
    use-read-only-response-cache: true
    # 用于一级响应缓存多久更新一次，默认30秒
    response-cache-update-interval-ms: 3000

server:
  port: 7001
  
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: 123456
