# 网关地址
GATEWAY: 192.168.0.111:8080
# PgSQL地址
PGSQL_ADDR: 192.168.0.111
# Redis地址
REDIS_ADDR: 192.168.0.111
# Kafka地址端口
KAFKA_ADDR_PORT: 192.168.0.111:9092

ES_ADDR_PORT: 192.168.0.111:9300
# FastDFS地址端口
FDFS_ADDR_PORT: 192.168.0.111:22122

# 下载图片URL地址端口
DOWN_URL_PREFIX: http:192.168.0.111
# web访问域名
DOMAIN_NAME: http://192.168.0.111

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.security: INFO

jasypt:
  encryptor:
    password: to@be@a@magic@master

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json
      min-request-size: 512000
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 200
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 500
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 500
          thread:
            timeoutInMilliseconds: 30000 # feign 超时控制

# kafka
kafka:
  consumer:
    servers: ${KAFKA_ADDR_PORT:localhost:9092}
    group-id: LAN_LIFE
    enable-auto-commit: true
    auto-commit-interval: 100
    session-timeout: 15000
    auto-offset-reset: earliest
  producer:
    retries-config: 1
    batch-size-config: 16384
    linger-ms-config: 1
    buffer-memory-config: 1024000

spring:
  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 数据库连接池配置
  datasource:
    url: jdbc:postgresql://${PGSQL_ADDR:localhost}:5432/postgres
    username: postgres
    password: ENC(/4KGc1VxnXQGvc2AcQmsB+gqcDSlTsUrbsHpUpuAQyA=)
    driverClassName: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    connection-properties: false
    filters: stat,config
  mybatis:
    type-aliases-package: cclub.anlan.lanlife.*.domain
    mapper-locations: classpath:mapper/**/*Mapper.xml
    config-location: classpath:config/mybatis-config.xml
  redis:
    host: ${REDIS_ADDR:localhost}
    port: 6371
    password: ENC(7Ec3ymUP729+ZWUmdmBQvENqBkc5wwmq)
    timeout: 2000
    database: 0
    connect-timeout: 2000
    read-timeout: 2000
    pool:
      max-idle: 10
      max-total: 50
      min-idle: 0
      maxActive: 50
      max-wait: 10000
      removeAbandoned: true
      removeAbandonedTimeout: 5000

management:
  security:
    enabled: false
  endpoints:
    actuator:
      enabled: true
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,1s,5s

# 图片存储
storage:
  type: fastdfs
  down-url-prefix: ${DOWN_URL_PREFIX:http://localhost:80}
  fdfs:
    connect-timeout: 10
    network-timeout: 30
    charset: UTF-8
    tracker-http-port: 8080
    tracker-server: ${FDFS_ADDR_PORT:localhost:22122}
    http-anti-steal-token: false
    http-secret-key:

fdfs:
  ## tracker地址，多个可fdfs.trackerList[0]、fdfs.trackerList[1]等方式配置
  trackerList: ${FDFS_ADDR_PORT:localhost:22122}
  ## 连接超时时间
  fdfs.connect-timeout: 5000
  ## 读取inputsream阻塞时间
  fdfs.so-timeout: 3000
  ## 连接池最大数量
  fdfs.pool.max-total: 100
  ## 每个tracker地址的最大连接数
  fdfs.pool.max-total-per-key: 10
  ## 连接耗尽时等待获取连接的最大毫秒数
  fdfs.pool.max-wait-millis: 25000
  ## 缩略图相关配置
  fdfs.thumbImage.height: 150
  fdfs.thumbImage.width: 150


# 允许访问跨域资源的域名
cors:
  allowed:
    origin: '*'
    header: '*'

# 需要转义放行的字符串
escape:
  characters:
    noInterceptor: <>


# i18n
i18n:
  messages:
    baseFolder: i18n
    basename: messageResource
    cache-seconds: -1
    encoding: UTF-8

# Rest template
rest:
  template:
    factory:
      readTimeout: 20000
      connectTimeout: 20000


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  ServerListRefreshInterval: 3000

credentials:
  oauth2:
    authen: N/A
  md5: MD5
  hmacmd5: HmacMD5
  des: DES

security:
  oauth2:
    resource:
      user-info-uri: http://${GATEWAY:localhost}/auth/user/current
