server:
  port: 8210
  servlet:
    session-timeout: 1800
    context-path: /basic

spring:
  # 数据库连接池配置
  datasource:
    initial-size: 10
    min-idle: 10
    max-active: 50
    # 数据库模式
    current-schema: basic

  # kafka
  kafka:
    consumer:
      group-id: LAN_LIFE_BASIC
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.consumer.servers}

# executer
executer:
  global:
    corePoolSize: 20
    maxPoolSize: 200
    queueCapacity: 2000
    keepAliveSeconds: 500

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

# OAuth2
security:
  oauth2:
    client:
      clientId: basic
      clientSecret: 123456
      accessTokenUri: http://${GATEWAY:localhost}/auth/oauth/token
      grant-type: client_credentials
      scope: server
  token:
    forceRevokeTokenUri: http://${GATEWAY:localhost}/auth/oauth/revokeTokenForce

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    # 下面选项建议打开，以监控 http 请求的 P99/P95 等，具体的时间分布可以根据实际情况设置
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
    # 在 Prometheus 中添加特别的 Labels
    tags:
      # 必须加上对应的应用名，因为需要以应用的维度来查看对应的监控
      application: basic

