server:
  port: 8880
  servlet:
    session-timeout: 1800
    context-path: /demo

spring:
  # 数据库连接池配置
  datasource:
    initial-size: 10
    min-idle: 10
    max-active: 50
    # 数据库模式
    current-schema: demo

  # kafka
  kafka:
    consumer:
      group-id: LAN_LIFE_DEMO
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.consumer.servers}

# executer
executer:
  global:
    corePoolSize: 20
    maxPoolSize: 200
    queueCapacity: 2000
    keepAliveSeconds: 500

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1


management:
  tags:
    application: demo
