server:
  port: 8220
  servlet:
    session-timeout: 1800
    context-path: /basic

spring:
  # 数据库连接池配置
  datasource:
    initial-size: 10
    min-idle: 10
    max-active: 50
    # 数据库模式
    current-schema: basic

  # kafka
  kafka:
    consumer:
      group-id: LAN_LIFE_BASIC
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.consumer.servers}

# executer
executer:
  global:
    corePoolSize: 20
    maxPoolSize: 200
    queueCapacity: 2000
    keepAliveSeconds: 500

endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1



