spring:
  application:
    name: demo
  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB
logging:
  config:
    classpath: log4j2.xml
  level:
    com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder: DEBUG
