@startuml

title AOP

autonumber

autoactivate on

skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantFontName Impact

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}


AbstractAutowireCapableBeanFactory -> AbstractAutowireCapableBeanFactory : applyBeanPostProcessorsBeforeInitialization

AbstractAutowireCapableBeanFactory -> AbstractAutoProxyCreator : postProcessAfterInitialization

AbstractAutoProxyCreator -> AbstractAutoProxyCreator : wrapIfNecessary

AbstractAutoProxyCreator -> AbstractAutoProxyCreator : getAdvicesAndAdvisorsForBean

AbstractAutoProxyCreator -> AbstractAdvisorAutoProxyCreator : findEligibleAdvisors

AbstractAdvisorAutoProxyCreator -> OrderComparator : doCompare

AbstractAutoProxyCreator -> AbstractAutoProxyCreator : createProxy

AbstractAutoProxyCreator -> ProxyFactory : getProxy

ProxyFactory -> DefaultAopProxyFactory : createAopProxy

DefaultAopProxyFactory -> AbstractAutoProxyCreator :  return AopProxy

JdkDynamicAopProxy -> JdkDynamicAopProxy :  invoke

JdkDynamicAopProxy -> AdvisedSupport :  getInterceptorsAndDynamicInterceptionAdvice

JdkDynamicAopProxy -> ReflectiveMethodInvocation :  proceed

JdkDynamicAopProxy -> before :  invoke

JdkDynamicAopProxy -> after :  invoke









@enduml