@startuml

title spring mvc

autonumber

autoactivate on

skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantFontName Impact

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

header Page Header


HttpServletBean -> HttpServletBean : init

HttpServletBean -> FrameworkServlet : initServletBean

FrameworkServlet -> FrameworkServlet : initWebApplicationContext

FrameworkServlet -> DispatcherServlet : onRefresh

DispatcherServlet -> DispatcherServlet : initStrategies

DispatcherServlet -> DispatcherServlet : initMultipartResolver

DispatcherServlet -> DispatcherServlet : initLocaleResolver

DispatcherServlet -> DispatcherServlet : initThemeResolver

DispatcherServlet -> DispatcherServlet : initHandlerMappings

DispatcherServlet -> DispatcherServlet : initHandlerAdapters

DispatcherServlet -> DispatcherServlet : initHandlerExceptionResolvers

DispatcherServlet -> DispatcherServlet : initRequestToViewNameTranslator

DispatcherServlet -> DispatcherServlet : initViewResolvers

DispatcherServlet -> DispatcherServlet : initFlashMapManager

web -> DispatcherServlet : 调用阶段

DispatcherServlet -> DispatcherServlet : doService

DispatcherServlet -> DispatcherServlet : getHandler

DispatcherServlet -> AbstractHandlerMapping : getHandler

AbstractHandlerMapping -> AbstractHandlerMapping : getHandlerExecutionChain

AbstractHandlerMapping -> DispatcherServlet : return HandlerExecutionChain

DispatcherServlet -> DispatcherServlet : getHandlerAdapter

DispatcherServlet -> HandlerInterceptor : preHandle

DispatcherServlet -> RequestMappingHandlerAdapter : handle

RequestMappingHandlerAdapter -> RequestMappingHandlerAdapter : getModelAndView

RequestMappingHandlerAdapter -> DispatcherServlet : 。。。

DispatcherServlet -> HandlerInterceptor : postHandle

HandlerInterceptor -> DispatcherServlet : 。。。

DispatcherServlet -> DispatcherServlet : processDispatchResult

DispatcherServlet -> DispatcherServlet : render







@enduml