spring:
  application: 
    name: config
  security:
    basic:
      enabled: false    #开启基于HTTP basic的认证
    user:
      name: user       #配置登陆的账号是user
      password: root   #配置登陆的密码是root
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）,默认30
    lease-renewal-interval-in-seconds: 4
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）, 默认90
    lease-expiration-duration-in-seconds: 12
  client:
    #eureka client刷新本地缓存时间，默认30
    registry-fetch-interval-seconds: 5
    serviceUrl:
#      defaultZone: http://user:123456@${EUREKA:182.254.215.204}:7001/eureka/
      defaultZone: http://user:123456@${EUREKA:127.0.0.1}:7001/eureka/
